version: '3'
networks:
  proxy:
    external:
      name: nginx-proxy

services:
  nginx:
    image: hub.goship.asia/dev-envnginx:dev
    build: .
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 80:80
    networks:
      - proxy
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

